from typing import List


class BaseConfig:
    """应用基础配置参数"""

    # 应用基础标题
    app_title: str = "布局助手"

    # 应用版本
    app_version: str = "0.2.2"

    # 部署环境 dev:开发环境  prod:生产环境  test:测试环境
    deploy_env: str = "dev"

    # 是否开启允许缩放画布  默认关闭
    enable_zoom_canvas: bool = False

    # 浏览器最低版本限制规则
    min_browser_versions: List[dict] = [
        {"browser": "Chrome", "version": 88},
        {"browser": "Firefox", "version": 78},
        {"browser": "Edge", "version": 100},
    ]

    # 是否基于min_browser_versions开启严格的浏览器类型限制
    # 不在min_browser_versions规则内的浏览器将被直接拦截
    strict_browser_type_check: bool = False

    # 布局助手配置参数
    layout_helper_config = {
        "show_grid": False,  # 是否开启网格辅助线
        "zoom_scale": 1.0,  # 缩放比例
        "drag_layout_list": {},  # 拖拽布局列表
        "drag_canvas": {
            "m_id": "",
            "m_name": "测试模版",
            "m_paper_type": "A4",
            "m_mm_w": "210",
            "m_mm_h": "297",
            "m_px_w": "210",
            "m_px_h": "297",
            "m_pages_num": "1",
            "m_Bkgrd_color": "#ffffff",
        },
    }

    # 组件配置参数
    element = {
        "text": "文本",
        "picture": "图片",
        "qrcode": "二维码",
        "barcode": "条形码",
        "table": "表格",
        "rectangle": "矩形",
        "transverse": "横线",
        "vertical": "竖线",
    }

    # 纸张
    paper = {
        # "A2": {"w_mm": 420, "h_mm": 594},
        "A3": {"w_mm": 297, "h_mm": 420},
        "A4": {"w_mm": 210, "h_mm": 297},
        "A5": {"w_mm": 148, "h_mm": 210},
        "A5/90": {"w_mm": 210, "h_mm": 148},
        "A4/3": {"w_mm": 210, "h_mm": 99},
        "自定义": {"w_mm": 210, "h_mm": 297},
    }

    # 模拟的API接口
    api = [
        {
            "group": "车辆检测报告类模拟API",
            "options": [
                {
                    "label": "VPIC",
                    "value": "https://vpic.nhtsa.dot.gov/api/vehicles/DecodeVinValues/1HGCM82633A123456?format=json",
                },
                {
                    "label": "NHTSA API",
                    "value": "https://api.nhtsa.gov/SafetyRatings/modelyear/2018/make/Honda/model/Accord",
                },
            ],
        },
        {
            "group": "医疗与健康类报告模拟API",
            "options": [
                {
                    "label": "FHIR",
                    "value": "https://hapi.fhir.org/baseR4/DiagnosticReport?patient=example&_format=json",
                },
            ],
        },
        {
            "group": "用户数据模拟API",
            "options": [
                {
                    "label": "用户数据",
                    "value": "https://randomuser.me/api/",
                },
                {
                    "label": "用户评论",
                    "value": "https://jsonplaceholder.typicode.com/posts",
                },
            ],
        },
    ]

    # 数据源配置
    data_source = {
        "人员信息": {
            "员工编号": "emp_id",
            "姓名": "emp_name",
            "性别": "emp_gender",
            "年龄": "emp_age",
            "生日": "emp_birthday",
            "手机号": "emp_mobile",
            "邮箱": "emp_email",
            "身份证号": "emp_idcard",
            "入职日期": "emp_hiredate",
            "离职日期": "emp_leavedate",
            "员工状态": "emp_status",
            "部门编号": "emp_dept_id",
            "直属上司编号": "emp_leader_id",
            "职务": "emp_job_title",
            "职级": "emp_job_level",
            "办公地点": "emp_office",
            "创建时间": "emp_create_time",
            "更新时间": "emp_update_time",
            "软删标记": "emp_deleted",
        },
        "设备信息": {
            "设备编号": "dev_id",
            "设备名称": "dev_name",
            "设备型号": "dev_model",
            "设备序列号": "dev_sn",
            "设备类型": "dev_type",
            "设备品牌": "dev_brand",
            "供应商编号": "dev_supplier_id",
            "购入日期": "dev_purchase_date",
            "购入价格": "dev_price",
            "使用年限": "dev_life_year",
            "设备状态": "dev_status",
            "使用人编号": "dev_user_id",
            "存放仓库编号": "dev_wh_id",
            "创建时间": "dev_create_time",
            "更新时间": "dev_update_time",
            "软删标记": "dev_deleted",
        },
        "订单信息": {
            "订单编号": "ord_id",
            "订单主题": "ord_subject",
            "客户编号": "ord_customer_id",
            "下单日期": "ord_date",
            "期望交付日期": "ord_expect_delivery",
            "交付日期": "ord_delivery_date",
            "订单金额": "ord_amount",
            "已收金额": "ord_paid_amount",
            "订单状态": "ord_status",
            "支付方式": "ord_pay_method",
            "物流单号": "ord_tracking_no",
            "收货地址": "ord_address",
            "收货人": "ord_receiver",
            "收货手机": "ord_receiver_mobile",
            "销售员编号": "ord_sales_id",
            "创建时间": "ord_create_time",
            "更新时间": "ord_update_time",
            "软删标记": "ord_deleted",
        },
        "合同信息": {
            "合同编号": "ctr_id",
            "合同名称": "ctr_name",
            "合同类型": "ctr_type",
            "甲方编号": "ctr_party_a_id",
            "乙方编号": "ctr_party_b_id",
            "签订日期": "ctr_sign_date",
            "生效日期": "ctr_effect_date",
            "到期日期": "ctr_expire_date",
            "合同金额": "ctr_amount",
            "付款方式": "ctr_pay_terms",
            "币种": "ctr_currency",
            "合同文件URL": "ctr_file_url",
            "合同状态": "ctr_status",
            "创建人编号": "ctr_create_emp",
            "审批人编号": "ctr_approve_emp",
            "创建时间": "ctr_create_time",
            "更新时间": "ctr_update_time",
            "软删标记": "ctr_deleted",
        },
        "发票信息": {
            "发票编号": "inv_id",
            "发票代码": "inv_code",
            "发票类型": "inv_type",
            "开票日期": "inv_date",
            "购方名称": "inv_buyer_name",
            "购方税号": "inv_buyer_taxno",
            "销方名称": "inv_seller_name",
            "销方税号": "inv_seller_taxno",
            "发票金额": "inv_amount",
            "税额": "inv_tax",
            "价税合计": "inv_total",
            "税率": "inv_rate",
            "发票状态": "inv_status",
            "关联订单编号": "inv_order_id",
            "关联合同编号": "inv_contract_id",
            "开票人编号": "inv_issuer_id",
            "发票PDF_URL": "inv_pdf_url",
            "创建时间": "inv_create_time",
            "更新时间": "inv_update_time",
            "软删标记": "inv_deleted",
        },
        "项目信息": {
            "项目编号": "prj_id",
            "项目名称": "prj_name",
            "项目类型": "prj_type",
            "客户编号": "prj_customer_id",
            "项目经理编号": "prj_manager_id",
            "开始日期": "prj_start_date",
            "计划结束日期": "prj_plan_end",
            "实际结束日期": "prj_actual_end",
            "项目预算": "prj_budget",
            "已用预算": "prj_cost",
            "项目状态": "prj_status",
            "风险等级": "prj_risk_level",
            "项目描述": "prj_desc",
            "创建人编号": "prj_create_emp",
            "创建时间": "prj_create_time",
            "更新时间": "prj_update_time",
            "软删标记": "prj_deleted",
        },
        "客户信息": {
            "客户编号": "cust_id",
            "客户名称": "cust_name",
            "客户类型": "cust_type",
            "国家": "cust_country",
            "省州": "cust_province",
            "城市": "cust_city",
            "详细地址": "cust_address",
            "联系人": "cust_contact",
            "联系电话": "cust_phone",
            "邮箱": "cust_email",
            "税号": "cust_taxno",
            "银行账号": "cust_bank_account",
            "开户行": "cust_bank_name",
            "信用等级": "cust_credit_level",
            "信用额度": "cust_credit_limit",
            "销售员编号": "cust_sales_id",
            "创建时间": "cust_create_time",
            "更新时间": "cust_update_time",
            "软删标记": "cust_deleted",
        },
        "供应商信息": {
            "供应商编号": "sup_id",
            "供应商名称": "sup_name",
            "供应商类型": "sup_type",
            "国家": "sup_country",
            "省州": "sup_province",
            "城市": "sup_city",
            "详细地址": "sup_address",
            "联系人": "sup_contact",
            "联系电话": "sup_phone",
            "邮箱": "sup_email",
            "税号": "sup_taxno",
            "银行账号": "sup_bank_account",
            "开户行": "sup_bank_name",
            "付款周期": "sup_pay_period",
            "质量等级": "sup_quality_level",
            "创建人编号": "sup_create_emp",
            "创建时间": "sup_create_time",
            "更新时间": "sup_update_time",
            "软删标记": "sup_deleted",
        },
        "仓库信息": {
            "仓库编号": "wh_id",
            "仓库名称": "wh_name",
            "仓库类型": "wh_type",
            "省州": "wh_province",
            "城市": "wh_city",
            "详细地址": "wh_address",
            "负责人编号": "wh_manager_id",
            "联系电话": "wh_phone",
            "仓库面积㎡": "wh_area",
            "温度范围": "wh_temp_range",
            "湿度范围": "wh_humidity_range",
            "仓库状态": "wh_status",
            "创建时间": "wh_create_time",
            "更新时间": "wh_update_time",
            "软删标记": "wh_deleted",
        },
        "部门信息": {
            "部门编号": "dept_id",
            "部门名称": "dept_name",
            "上级部门编号": "dept_parent_id",
            "部门层级": "dept_level",
            "负责人编号": "dept_manager_id",
            "联系电话": "dept_phone",
            "办公地点": "dept_office",
            "部门预算": "dept_budget",
            "部门描述": "dept_desc",
            "成立日期": "dept_found_date",
            "部门状态": "dept_status",
            "创建时间": "dept_create_time",
            "更新时间": "dept_update_time",
            "软删标记": "dept_deleted",
        },
        "产品信息": {
            "产品编号": "prod_id",
            "产品名称": "prod_name",
            "产品类别": "prod_category",
            "品牌": "prod_brand",
            "型号": "prod_model",
            "单位": "prod_unit",
            "规格": "prod_spec",
            "条形码": "prod_barcode",
            "保质期天数": "prod_shelf_life",
            "采购价": "prod_purchase_price",
            "销售价": "prod_sale_price",
            "最低库存": "prod_min_stock",
            "最高库存": "prod_max_stock",
            "产品状态": "prod_status",
            "创建时间": "prod_create_time",
            "更新时间": "prod_update_time",
            "软删标记": "prod_deleted",
        },
        "库存信息": {
            "库存编号": "stk_id",
            "仓库编号": "stk_wh_id",
            "产品编号": "stk_prod_id",
            "库存数量": "stk_qty",
            "冻结数量": "stk_freeze_qty",
            "可用数量": "stk_available_qty",
            "最近入库时间": "stk_last_in",
            "最近出库时间": "stk_last_out",
            "盘点时间": "stk_check_time",
            "创建时间": "stk_create_time",
            "更新时间": "stk_update_time",
            "软删标记": "stk_deleted",
        },
        "采购申请": {
            "申请编号": "par_id",
            "申请主题": "par_subject",
            "申请部门编号": "par_dept_id",
            "申请人编号": "par_emp_id",
            "期望到货日期": "par_expect_date",
            "申请原因": "par_reason",
            "采购总金额": "par_total_amount",
            "申请状态": "par_status",
            "审批人编号": "par_approver_id",
            "审批意见": "par_approve_comment",
            "审批时间": "par_approve_time",
            "创建时间": "par_create_time",
            "更新时间": "par_update_time",
            "软删标记": "par_deleted",
        },
        "采购订单": {
            "采购单编号": "po_id",
            "采购主题": "po_subject",
            "供应商编号": "po_supplier_id",
            "付款方式": "po_pay_terms",
            "交货地址": "po_delivery_addr",
            "交货日期": "po_delivery_date",
            "采购金额": "po_amount",
            "已付金额": "po_paid_amount",
            "采购单状态": "po_status",
            "采购员编号": "po_buyer_id",
            "关联申请编号": "po_apply_id",
            "合同编号": "po_contract_id",
            "创建时间": "po_create_time",
            "更新时间": "po_update_time",
            "软删标记": "po_deleted",
        },
        "入库单": {
            "入库单编号": "grn_id",
            "入库类型": "grn_type",
            "关联采购单编号": "grn_po_id",
            "关联退货单编号": "grn_rtn_id",
            "仓库编号": "grn_wh_id",
            "入库日期": "grn_date",
            "入库金额": "grn_amount",
            "入库单状态": "grn_status",
            "验收人编号": "grn_checker_id",
            "验收备注": "grn_remark",
            "创建时间": "grn_create_time",
            "更新时间": "grn_update_time",
            "软删标记": "grn_deleted",
        },
        "出库单": {
            "出库单编号": "gdn_id",
            "出库类型": "gdn_type",
            "关联订单编号": "gdn_order_id",
            "仓库编号": "gdn_wh_id",
            "出库日期": "gdn_date",
            "出库金额": "gdn_amount",
            "出库单状态": "gdn_status",
            "拣货人编号": "gdn_picker_id",
            "复核人编号": "gdn_reviewer_id",
            "物流单号": "gdn_tracking_no",
            "创建时间": "gdn_create_time",
            "更新时间": "gdn_update_time",
            "软删标记": "gdn_deleted",
        },
        "付款单": {
            "付款单编号": "pay_id",
            "付款主题": "pay_subject",
            "关联采购单编号": "pay_po_id",
            "关联合同编号": "pay_contract_id",
            "供应商编号": "pay_supplier_id",
            "付款方式": "pay_method",
            "付款金额": "pay_amount",
            "付款日期": "pay_date",
            "付款账户": "pay_account",
            "交易流水号": "pay_serial_no",
            "付款状态": "pay_status",
            "经办人编号": "pay_emp_id",
            "创建时间": "pay_create_time",
            "更新时间": "pay_update_time",
            "软删标记": "pay_deleted",
        },
        "收款单": {
            "收款单编号": "rec_id",
            "收款主题": "rec_subject",
            "关联订单编号": "rec_order_id",
            "关联合同编号": "rec_contract_id",
            "客户编号": "rec_customer_id",
            "收款方式": "rec_method",
            "收款金额": "rec_amount",
            "收款日期": "rec_date",
            "收款账户": "rec_account",
            "交易流水号": "rec_serial_no",
            "收款状态": "rec_status",
            "经办人编号": "rec_emp_id",
            "创建时间": "rec_create_time",
            "更新时间": "rec_update_time",
            "软删标记": "rec_deleted",
        },
        "费用报销": {
            "报销单编号": "exp_id",
            "报销主题": "exp_subject",
            "报销人编号": "exp_emp_id",
            "部门编号": "exp_dept_id",
            "费用类型": "exp_type",
            "发生日期": "exp_happen_date",
            "报销金额": "exp_amount",
            "发票张数": "exp_invoice_cnt",
            "报销说明": "exp_desc",
            "审批人编号": "exp_approver_id",
            "审批意见": "exp_approve_comment",
            "审批时间": "exp_approve_time",
            "报销状态": "exp_status",
            "创建时间": "exp_create_time",
            "更新时间": "exp_update_time",
            "软删标记": "exp_deleted",
        },
        "考勤记录": {
            "考勤编号": "att_id",
            "员工编号": "att_emp_id",
            "考勤日期": "att_date",
            "班次": "att_shift",
            "上班打卡时间": "att_checkin",
            "下班打卡时间": "att_checkout",
            "迟到分钟": "att_late_min",
            "早退分钟": "att_leave_early_min",
            "加班分钟": "att_overtime_min",
            "缺勤标记": "att_absent_flag",
            "请假单编号": "att_leave_id",
            "外勤标记": "att_out_flag",
            "备注": "att_remark",
            "创建时间": "att_create_time",
            "更新时间": "att_update_time",
            "软删标记": "att_deleted",
        },
        "请假申请": {
            "请假单编号": "leave_id",
            "员工编号": "leave_emp_id",
            "请假类型": "leave_type",
            "开始时间": "leave_start_time",
            "结束时间": "leave_end_time",
            "请假天数": "leave_days",
            "请假原因": "leave_reason",
            "审批人编号": "leave_approver_id",
            "审批意见": "leave_approve_comment",
            "审批时间": "leave_approve_time",
            "请假状态": "leave_status",
            "创建时间": "leave_create_time",
            "更新时间": "leave_update_time",
            "软删标记": "leave_deleted",
        },
        "加班申请": {
            "加班单编号": "ot_id",
            "员工编号": "ot_emp_id",
            "加班日期": "ot_date",
            "开始时间": "ot_start_time",
            "结束时间": "ot_end_time",
            "加班小时": "ot_hours",
            "加班原因": "ot_reason",
            "审批人编号": "ot_approver_id",
            "审批意见": "ot_approve_comment",
            "审批时间": "ot_approve_time",
            "加班状态": "ot_status",
            "创建时间": "ot_create_time",
            "更新时间": "ot_update_time",
            "软删标记": "ot_deleted",
        },
        "公告通知": {
            "公告编号": "notice_id",
            "公告标题": "notice_title",
            "公告类型": "notice_type",
            "优先级": "notice_priority",
            "生效时间": "notice_effect_time",
            "失效时间": "notice_expire_time",
            "公告内容": "notice_content",
            "附件URL": "notice_attach_url",
            "发布人编号": "notice_publisher_id",
            "已读人数": "notice_read_cnt",
            "公告状态": "notice_status",
            "创建时间": "notice_create_time",
            "更新时间": "notice_update_time",
            "软删标记": "notice_deleted",
        },
        "系统用户": {
            "用户编号": "usr_id",
            "登录账号": "usr_account",
            "登录密码": "usr_password_hash",
            "用户类型": "usr_type",
            "姓名": "usr_name",
            "手机号": "usr_mobile",
            "邮箱": "usr_email",
            "头像URL": "usr_avatar_url",
            "所属部门编号": "usr_dept_id",
            "岗位": "usr_post",
            "最后登录时间": "usr_last_login",
            "最后登录IP": "usr_last_ip",
            "密码错误次数": "usr_pwd_err_cnt",
            "账号状态": "usr_status",
            "创建人编号": "usr_create_emp",
            "创建时间": "usr_create_time",
            "更新时间": "usr_update_time",
            "软删标记": "usr_deleted",
        },
        "角色权限": {
            "角色编号": "role_id",
            "角色名称": "role_name",
            "角色编码": "role_code",
            "角色类型": "role_type",
            "数据权限范围": "role_data_scope",
            "角色描述": "role_desc",
            "排序": "role_sort",
            "角色状态": "role_status",
            "创建人编号": "role_create_emp",
            "创建时间": "role_create_time",
            "更新时间": "role_update_time",
            "软删标记": "role_deleted",
        },
        "操作日志": {
            "日志编号": "log_id",
            "用户编号": "log_usr_id",
            "用户姓名": "log_usr_name",
            "操作模块": "log_module",
            "操作类型": "log_action",
            "操作描述": "log_desc",
            "请求URL": "log_request_url",
            "请求方法": "log_request_method",
            "请求IP": "log_ip",
            "请求耗时ms": "log_duration",
            "用户代理": "log_user_agent",
            "操作结果": "log_result",
            "操作时间": "log_create_time",
        },
        "消息中心": {
            "消息编号": "msg_id",
            "接收人编号": "msg_receiver_id",
            "消息标题": "msg_title",
            "消息内容": "msg_content",
            "消息类型": "msg_type",
            "是否已读": "msg_read_flag",
            "读取时间": "msg_read_time",
            "跳转链接": "msg_jump_url",
            "发送人编号": "msg_sender_id",
            "发送时间": "msg_send_time",
            "创建时间": "msg_create_time",
            "软删标记": "msg_deleted",
        },
        "附件管理": {
            "附件编号": "attm_id",
            "业务类型": "attm_biz_type",
            "业务主键": "attm_biz_id",
            "原始文件名": "attm_orig_name",
            "存储文件名": "attm_save_name",
            "文件大小Byte": "attm_size",
            "文件类型": "attm_mime_type",
            "存储路径": "attm_path",
            "下载次数": "attm_down_cnt",
            "上传人编号": "attm_upload_emp",
            "上传时间": "attm_upload_time",
            "软删标记": "attm_deleted",
        },
    }
